const GeoLayout mr_i_iris_armature_001_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_iris_001_switch_option_001_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_iris_armature_002_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_iris_002_switch_option_002_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_iris_armature_003_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_iris_003_switch_option_003_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_iris_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mr_i_iris_000_displaylist_001_mesh),
			GEO_SWITCH_CASE(20, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mr_i_iris_000_displaylist_mesh),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, mr_i_iris_armature_001_switch_option),
				GEO_BRANCH(1, mr_i_iris_armature_002_switch_option),
				GEO_BRANCH(1, mr_i_iris_armature_003_switch_option),
				GEO_BRANCH(1, mr_i_iris_armature_002_switch_option),
				GEO_BRANCH(1, mr_i_iris_armature_001_switch_option),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mr_i_iris_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_iris_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
