const GeoLayout wiggler_body_geo[] = {
	GEO_SHADOW(0, 150, 100),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, wiggler_body_000_displaylist_mesh),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 0, 51, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wiggler_body_000_offset_003_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_body_000_offset_004_skinned),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 39, 0, 0, wiggler_body_000_offset_004_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 41, 0, 0, wiggler_body_000_offset_005_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 0, -49, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wiggler_body_000_offset_006_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_body_000_offset_007_skinned),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 39, 0, 0, wiggler_body_000_offset_007_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 41, 0, 0, wiggler_body_000_offset_008_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_body_material_revert_render_settings),
	GEO_DISPLAY_LIST(LAYER_ALPHA, wiggler_body_material_revert_render_settings),
	GEO_END(),
};
