// 0x1600013C
const GeoLayout yellow_coin_armature_001_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_001_switch_option_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_001_switch_option_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_armature_002_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_002_switch_option_002_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_002_switch_option_002_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_armature_003_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_003_switch_option_003_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_003_switch_option_003_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_armature_004_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_004_switch_option_004_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_004_switch_option_004_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_armature_005_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_005_switch_option_005_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_005_switch_option_005_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_armature_006_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_006_switch_option_006_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_006_switch_option_006_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_armature_007_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_007_switch_option_007_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_007_switch_option_007_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yellow_coin_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 50),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(8, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_RENDER_RANGE(-2048, 1500),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
					GEO_RENDER_RANGE(1500, 32767),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, yellow_coin_armature_001_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_002_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_003_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_004_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_005_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_006_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_007_switch_option),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};


// 0x160001A0
const GeoLayout yellow_coin_no_shadow_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(8, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_RENDER_RANGE(-2048, 1500),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
					GEO_RENDER_RANGE(1500, 32767),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_low_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, yellow_coin_armature_001_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_002_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_003_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_004_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_005_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_006_switch_option),
				GEO_BRANCH(1, yellow_coin_armature_007_switch_option),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

// 0x16000200
const GeoLayout blue_coin_armature_001_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_001_switch_option_001_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_armature_002_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_002_switch_option_002_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_armature_003_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_003_switch_option_003_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_armature_004_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_004_switch_option_004_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_armature_005_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_005_switch_option_005_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_armature_006_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_006_switch_option_006_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_armature_007_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_007_switch_option_007_displaylist_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blue_coin_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 50),
		GEO_OPEN_NODE(),
			GEO_SCALE(0x00, 98304),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(8, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, blue_coin_armature_001_switch_option),
					GEO_BRANCH(1, blue_coin_armature_002_switch_option),
					GEO_BRANCH(1, blue_coin_armature_003_switch_option),
					GEO_BRANCH(1, blue_coin_armature_004_switch_option),
					GEO_BRANCH(1, blue_coin_armature_005_switch_option),
					GEO_BRANCH(1, blue_coin_armature_006_switch_option),
					GEO_BRANCH(1, blue_coin_armature_007_switch_option),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

// 0x16000264
const GeoLayout blue_coin_no_shadow_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(8, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, blue_coin_000_displaylist_mesh),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, blue_coin_armature_001_switch_option),
				GEO_BRANCH(1, blue_coin_armature_002_switch_option),
				GEO_BRANCH(1, blue_coin_armature_003_switch_option),
				GEO_BRANCH(1, blue_coin_armature_004_switch_option),
				GEO_BRANCH(1, blue_coin_armature_005_switch_option),
				GEO_BRANCH(1, blue_coin_armature_006_switch_option),
				GEO_BRANCH(1, blue_coin_armature_007_switch_option),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, yellow_coin_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

// 0x160002C4
const GeoLayout red_coin_armature_001_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_001_switch_option_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_001_switch_option_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_armature_002_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_002_switch_option_002_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_002_switch_option_002_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_armature_003_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_003_switch_option_003_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_003_switch_option_003_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_armature_004_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_004_switch_option_004_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_004_switch_option_004_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_armature_005_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_005_switch_option_005_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_005_switch_option_005_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_armature_006_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_006_switch_option_006_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_006_switch_option_006_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_armature_007_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 1500),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_007_switch_option_007_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(1500, 32767),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_007_switch_option_007_displaylist_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout red_coin_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 50),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(8, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_RENDER_RANGE(-2048, 1500),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
					GEO_RENDER_RANGE(1500, 32767),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, red_coin_armature_001_switch_option),
				GEO_BRANCH(1, red_coin_armature_002_switch_option),
				GEO_BRANCH(1, red_coin_armature_003_switch_option),
				GEO_BRANCH(1, red_coin_armature_004_switch_option),
				GEO_BRANCH(1, red_coin_armature_005_switch_option),
				GEO_BRANCH(1, red_coin_armature_006_switch_option),
				GEO_BRANCH(1, red_coin_armature_007_switch_option),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};


// 0x16000328
const GeoLayout red_coin_no_shadow_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(8, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_RENDER_RANGE(-2048, 1500),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
					GEO_RENDER_RANGE(1500, 32767),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_low_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, red_coin_armature_001_switch_option),
				GEO_BRANCH(1, red_coin_armature_002_switch_option),
				GEO_BRANCH(1, red_coin_armature_003_switch_option),
				GEO_BRANCH(1, red_coin_armature_004_switch_option),
				GEO_BRANCH(1, red_coin_armature_005_switch_option),
				GEO_BRANCH(1, red_coin_armature_006_switch_option),
				GEO_BRANCH(1, red_coin_armature_007_switch_option),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};