const GeoLayout klepto_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 250),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, klepto_000_offset_001_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 62, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 31, 15, 0, klepto_000_offset_003_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -15, 0, klepto_000_offset_004_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -3, 17, 17, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, klepto_000_offset_005_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, klepto_000_offset_006_skinned),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, klepto_000_offset_006_mesh),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(4, geo_switch_anim_state),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SCALE(0x00, 16384),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_offset_klepto_held_object),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, 100, 0, 180, 270, 0, mario_cap_seg3_dl_03022F48),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SCALE(0x00, 16384),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_offset_klepto_held_object),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, 100, 0, 180, 270, 0, star_000_displaylist_mesh),
												GEO_ASM(0, geo_offset_klepto_held_object),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, 0, 100, 0, 180, 270, 0, star_001_displaylist_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SCALE(0x00, 16384),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_offset_klepto_held_object),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, 100, 0, 180, 270, 0, transparent_star_000_displaylist_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -3, 17, -17, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, klepto_000_offset_007_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, klepto_000_offset_008_skinned),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, klepto_000_offset_008_mesh),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 49, -9, -17, NULL),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, klepto_000_offset_009_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, klepto_000_offset_010_skinned),
									GEO_ANIMATED_PART(LAYER_ALPHA, 34, 0, 0, klepto_000_offset_010_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, klepto_000_offset_011_skinned),
										GEO_ANIMATED_PART(LAYER_ALPHA, 79, 0, 0, klepto_000_offset_011_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 49, -9, 17, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, klepto_000_offset_012_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, klepto_000_offset_013_skinned),
								GEO_ANIMATED_PART(LAYER_ALPHA, 34, 0, 0, klepto_000_offset_013_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, klepto_000_offset_014_skinned),
									GEO_ANIMATED_PART(LAYER_ALPHA, 79, 0, 0, klepto_000_offset_014_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, klepto_002_offset_003_mesh),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, klepto_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, klepto_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
